[build]
  # Eseguiamo la build solo per il frontend usando il filtro di pnpm
  command = "pnpm run build --filter frontend"
  
  # Specifichiamo dove Netlify trover√† l'output di Next.js
  publish = "frontend/.next"

[build.environment]
  # Forza Netlify a usare pnpm e specifica la versione se necessario
  NPM_FLAGS = "--version" 

[[plugins]]
  package = "@netlify/plugin-nextjs"
