[build]
  # Eseguiamo la build solo per il frontend usando il filtro di pnpm
  # command = "pnpm run build --filter frontend"
  # command = "pnpm install && bin/setup_frontend.sh && pnpm --filter frontend build"
  command = "pnpm install && pnpm run app_install --filter frontend"

  # Specifichiamo dove Netlify trover√† l'output di Next.js
  publish = "frontend/public"

[build.environment]
  # Forza Netlify a usare pnpm e specifica la versione se necessario
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-nextjs"
